"""Tests for scripts/generate_graphql_inputs.py."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SCRIPT = _REPO_ROOT / "scripts" / "generate_graphql_inputs.py"
_spec = importlib.util.spec_from_file_location("generate_graphql_inputs", _SCRIPT)
assert _spec and _spec.loader
_gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gen)


def _snapshot() -> dict:
    return json.loads(_gen.SNAPSHOT_PATH.read_text())


# --- the drift guard itself -------------------------------------------------


def test_generated_models_match_the_committed_snapshot():
    """The check CI runs, run here so a stale commit fails the suite too."""
    assert _gen.command_check() == 0


def test_every_root_type_is_in_the_snapshot():
    snapshot = _snapshot()
    assert sorted(_gen.ROOT_INPUT_TYPES) == snapshot["roots"]
    for root in _gen.ROOT_INPUT_TYPES:
        assert root in snapshot["inputs"]


def test_snapshot_is_closed_over_its_references():
    """Every input object and enum a field names is itself in the snapshot."""
    snapshot = _snapshot()
    known = set(snapshot["inputs"]) | set(snapshot["enums"]) | set(_gen.SCALAR_TYPES)
    for name, spec in snapshot["inputs"].items():
        for field in spec["fields"]:
            referenced = _gen._named_type(field["type"])
            assert referenced in known, f"{name}.{field['name']} -> {referenced}"


# --- type mapping -----------------------------------------------------------


@pytest.mark.parametrize(
    ("type_ref", "expected", "required"),
    [
        ("String", "str", False),
        ("String!", "str", True),
        ("ID!", "PipefyGraphQLId", True),
        ("Int", "int", False),
        ("Float", "float", False),
        ("Boolean", "bool", False),
        ("JSON", "GraphQLJson", False),
        # A nullable list of nullable strings, faithful to `[String]`.
        ("[String]", "list[str | None]", False),
        # `[String!]!` keeps both non-nulls: no `| None` inside or out.
        ("[String!]!", "list[str]", True),
        # `[[ID]]` — the shape createFieldCondition uses for expressions_structure.
        ("[[ID]]", "list[list[PipefyGraphQLId | None] | None]", False),
        ("ConditionInput", "ConditionInput", False),
        # The one lowercase type name in the schema takes the Python spelling.
        ("createFieldConditionInput", "CreateFieldConditionInput", False),
        # A GraphQL enum is a soft enum: typed str, any value sent.
        ("Colors", "str", False),
    ],
)
def test_python_type_mapping(type_ref, expected, required):
    assert _gen.python_type(type_ref, _snapshot()) == (expected, required)


def test_unmapped_scalar_is_a_hard_failure():
    """A new custom scalar must be mapped deliberately, not guessed at."""
    with pytest.raises(SystemExit, match="Money"):
        _gen.python_type("Money", {"inputs": {}, "enums": {}})


# --- naming -----------------------------------------------------------------


def test_python_keyword_field_gets_an_alias():
    assert _gen.field_attribute("from") == ("from_", "from")


@pytest.mark.parametrize("name", ["label", "phase_id", "clientMutationId"])
def test_ordinary_field_keeps_its_wire_name(name):
    assert _gen.field_attribute(name) == (name, None)


def test_enum_constant_name():
    assert _gen.enum_constant_name("Colors") == "COLORS_VALUES"
    assert (
        _gen.enum_constant_name("PublicFormSubmitterEmailCollectionMethod")
        == "PUBLIC_FORM_SUBMITTER_EMAIL_COLLECTION_METHOD_VALUES"
    )


# --- descriptions -----------------------------------------------------------


def test_bullet_list_is_folded_into_the_sentence():
    raw = "The condition action\n\n      Valid options:\n      - hide\n      - show"
    assert (
        _gen.clean_description(raw) == "The condition action Valid options: hide, show."
    )


def test_bullets_with_no_colon_get_one():
    assert _gen.clean_description("Pick one\n- a\n- b") == "Pick one: a, b."


def test_relay_boilerplate_description_is_dropped():
    assert _gen.clean_description("Autogenerated input type of UpdatePipe") == ""


def test_empty_description_stays_empty():
    assert _gen.clean_description(None) == ""
    assert _gen.clean_description("   ") == ""


# --- snapshot building ------------------------------------------------------


def _schema_type(name, kind, fields=None, enum_values=None):
    return {
        "name": name,
        "kind": kind,
        "description": None,
        "enumValues": [{"name": v} for v in (enum_values or [])] or None,
        "inputFields": fields,
    }


def _scalar_ref(name, non_null=False):
    ref = {"kind": "SCALAR", "name": name, "ofType": None}
    return {"kind": "NON_NULL", "name": None, "ofType": ref} if non_null else ref


def test_build_snapshot_walks_transitively(monkeypatch):
    monkeypatch.setattr(_gen, "ROOT_INPUT_TYPES", ("RootInput",))
    schema = [
        _schema_type(
            "RootInput",
            "INPUT_OBJECT",
            [
                {
                    "name": "nested",
                    "description": None,
                    "defaultValue": None,
                    "type": {
                        "kind": "INPUT_OBJECT",
                        "name": "NestedInput",
                        "ofType": None,
                    },
                },
                {
                    "name": "shade",
                    "description": None,
                    "defaultValue": None,
                    "type": {"kind": "ENUM", "name": "Shade", "ofType": None},
                },
            ],
        ),
        _schema_type(
            "NestedInput",
            "INPUT_OBJECT",
            [
                {
                    "name": "id",
                    "description": None,
                    "defaultValue": None,
                    "type": _scalar_ref("ID", non_null=True),
                }
            ],
        ),
        _schema_type("Shade", "ENUM", enum_values=["light", "dark"]),
        _schema_type("Unrelated", "INPUT_OBJECT", []),
    ]
    snapshot = _gen.build_snapshot(schema)
    assert set(snapshot["inputs"]) == {"RootInput", "NestedInput"}
    assert snapshot["enums"] == {"Shade": ["light", "dark"]}
    assert snapshot["inputs"]["NestedInput"]["fields"][0]["type"] == "ID!"


def test_build_snapshot_rejects_a_root_that_is_not_an_input_object(monkeypatch):
    monkeypatch.setattr(_gen, "ROOT_INPUT_TYPES", ("Pipe",))
    with pytest.raises(SystemExit, match="Pipe is not an INPUT_OBJECT"):
        _gen.build_snapshot([_schema_type("Pipe", "OBJECT")])


@pytest.mark.parametrize(
    ("node", "expected"),
    [
        ({"kind": "SCALAR", "name": "String", "ofType": None}, "String"),
        ({"kind": "NON_NULL", "name": None, "ofType": _scalar_ref("ID")}, "ID!"),
        (
            {
                "kind": "LIST",
                "name": None,
                "ofType": {
                    "kind": "NON_NULL",
                    "name": None,
                    "ofType": _scalar_ref("ID"),
                },
            },
            "[ID!]",
        ),
    ],
)
def test_type_ref_rendering(node, expected):
    assert _gen._type_ref(node) == expected


# --- generated output -------------------------------------------------------


def test_generated_files_carry_the_do_not_edit_header():
    for path in (_gen.GENERATED_PATH, _gen.INIT_PATH):
        assert path.read_text().startswith("# @generated by")


def test_check_reports_a_hand_edit(tmp_path, monkeypatch):
    stale = tmp_path / "_generated.py"
    stale.write_text("# someone edited this by hand\n")
    monkeypatch.setattr(_gen, "GENERATED_PATH", stale)
    assert _gen.command_check() == 1
