"""Pipefy GraphQL SDK: typed client, models, and service layer for Pipefy's APIs."""

from __future__ import annotations

__version__ = "0.5.0-beta.1"

from pipefy_sdk.client import PipefyClient, PipefyEngine
from pipefy_sdk.exceptions import PipefyAPIError, PipefyError
from pipefy_sdk.field_filters import (
    filter_editable_field_definitions,
    filter_fields_by_definitions,
    skipped_field_ids,
)
from pipefy_sdk.graphql_executor import PipefyGraphQLError
from pipefy_sdk.graphql_problem import (
    GraphQLProblem,
    GraphQLProblemKind,
    classify_exception,
    classify_graphql_error_dicts,
)
from pipefy_sdk.models import (
    CONDITION_OPERATIONS,
    Attachment,
    AttachmentTarget,
    AttachmentUploadError,
    AttachmentUploadResult,
    AttachmentUploadStep,
    AutomationConditionInput,
    AutomationEventParamsInput,
    BehaviorInput,
    BehaviorPayload,
    CardTarget,
    CommentInput,
    ConditionExpressionInput,
    CreateAiAgentInput,
    CreateAiAutomationInput,
    CreatePortalElementInput,
    CreateSendTaskAutomationInput,
    DataLookupCondition,
    DeleteCommentInput,
    MemberInvite,
    NonBlankStr,
    PipefyId,
    PresignedUploadTarget,
    TableRecordTarget,
    UpdateAiAgentInput,
    UpdateAiAutomationInput,
    UpdateCommentInput,
    UpdatePortalElementInput,
    UploadAttachmentToCardInput,
    UploadAttachmentToTableRecordInput,
    infer_content_type,
)
from pipefy_sdk.models.form import create_form_model
from pipefy_sdk.queries.observability_queries import (
    AUTOMATION_EVENT_IDS,
    AUTOMATION_EXECUTION_METRICS_PERIODS,
    AUTOMATION_SORT_BY,
    AUTOMATION_SORT_ORDER,
)
from pipefy_sdk.services.automation_graphql_types import (
    AutomationActionRow,
    AutomationEventRow,
    AutomationRuleRecord,
    AutomationRuleSummary,
)
from pipefy_sdk.services.observability_export_csv import download_bytes, stream_bytes
from pipefy_sdk.services.observability_service import (
    AUTOMATION_EXECUTION_METRICS_MAX_PAGE_SIZE,
)
from pipefy_sdk.services.table_service import (
    UPDATE_TABLE_RECORD_ALLOWED_FIELD_KEYS,
    UPDATE_TABLE_RECORD_FIELDS_ERROR_MESSAGE,
)
from pipefy_sdk.services.types import (
    ActiveLlmProviderPayload,
    AiAgentGraphPayload,
    CardSearch,
    KnowledgeBaseAccessProbeResult,
    KnowledgeBaseDataLookupPayload,
    KnowledgeBaseDeleteResult,
    KnowledgeBaseDocumentPayload,
    KnowledgeBaseDocumentUploadError,
    KnowledgeBasePayload,
    KnowledgeBasePlainTextPayload,
    LlmProviderMutationResult,
    LlmProviderPayload,
    LlmProvidersResult,
    LlmProviderWritePayload,
    MePayload,
    ProviderAccessProbeResult,
    ProviderDependenciesResult,
    copy_card_search,
)
from pipefy_sdk.settings import PipefySettings

__all__ = [
    "__version__",
    "AiAgentGraphPayload",
    "AUTOMATION_EVENT_IDS",
    "AUTOMATION_EXECUTION_METRICS_MAX_PAGE_SIZE",
    "AUTOMATION_EXECUTION_METRICS_PERIODS",
    "AUTOMATION_SORT_BY",
    "AUTOMATION_SORT_ORDER",
    "Attachment",
    "AttachmentTarget",
    "AttachmentUploadError",
    "AttachmentUploadResult",
    "AttachmentUploadStep",
    "PresignedUploadTarget",
    "UPDATE_TABLE_RECORD_ALLOWED_FIELD_KEYS",
    "UPDATE_TABLE_RECORD_FIELDS_ERROR_MESSAGE",
    "AutomationActionRow",
    "AutomationConditionInput",
    "AutomationEventParamsInput",
    "AutomationEventRow",
    "AutomationRuleRecord",
    "AutomationRuleSummary",
    "BehaviorInput",
    "BehaviorPayload",
    "CardSearch",
    "CardTarget",
    "CommentInput",
    "CONDITION_OPERATIONS",
    "ConditionExpressionInput",
    "CreateAiAgentInput",
    "CreateAiAutomationInput",
    "CreatePortalElementInput",
    "CreateSendTaskAutomationInput",
    "DataLookupCondition",
    "DeleteCommentInput",
    "GraphQLProblem",
    "GraphQLProblemKind",
    "KnowledgeBaseAccessProbeResult",
    "KnowledgeBaseDataLookupPayload",
    "KnowledgeBaseDeleteResult",
    "KnowledgeBaseDocumentPayload",
    "KnowledgeBaseDocumentUploadError",
    "KnowledgeBasePayload",
    "KnowledgeBasePlainTextPayload",
    "ActiveLlmProviderPayload",
    "LlmProviderMutationResult",
    "LlmProviderPayload",
    "LlmProvidersResult",
    "LlmProviderWritePayload",
    "ProviderAccessProbeResult",
    "ProviderDependenciesResult",
    "classify_exception",
    "classify_graphql_error_dicts",
    "download_bytes",
    "filter_editable_field_definitions",
    "filter_fields_by_definitions",
    "MePayload",
    "MemberInvite",
    "NonBlankStr",
    "PipefyAPIError",
    "PipefyClient",
    "PipefyEngine",
    "PipefyError",
    "PipefyGraphQLError",
    "PipefyId",
    "PipefySettings",
    "TableRecordTarget",
    "UpdateAiAgentInput",
    "UpdateAiAutomationInput",
    "UpdateCommentInput",
    "UpdatePortalElementInput",
    "UploadAttachmentToCardInput",
    "UploadAttachmentToTableRecordInput",
    "copy_card_search",
    "create_form_model",
    "infer_content_type",
    "skipped_field_ids",
    "stream_bytes",
]
