# @generated by scripts/generate_graphql_inputs.py — do not edit.
"""Typed inputs for the Pipefy GraphQL mutations the SDK writes to.

Each model mirrors one GraphQL input object: same field names, same
requiredness, same nesting. Constructing one rejects a misspelled or
unknown field by name, before any request is made.

`_generated.py` is written from a snapshot of the live schema by
`scripts/generate_graphql_inputs.py`. `_base.py` holds the parts that needed a
decision rather than a mapping. Neither this file nor `_generated.py` is
edited by hand.

`ConditionExpressionInput` here is the schema mirror. The separate
`pipefy_sdk.ConditionExpressionInput` is an older permissive model that the AI
automation surface still uses; the two converge when those methods take typed
inputs.
"""

from __future__ import annotations

from pipefy_sdk.graphql_inputs._base import (
    GraphQLInput,
    GraphQLJson,
    PipefyGraphQLId,
    describe_input_rejection,
)
from pipefy_sdk.graphql_inputs._generated import (
    COLORS_VALUES,
    PUBLIC_FORM_SUBMITTER_EMAIL_COLLECTION_METHOD_VALUES,
    ConditionExpressionInput,
    ConditionInput,
    CreateFieldConditionInput,
    CreatePhaseFieldInput,
    FieldConditionActionInput,
    PublicFormSettingsInput,
    RepoPreferenceInput,
    UpdateFieldConditionInput,
    UpdateLabelInput,
    UpdatePhaseFieldInput,
    UpdatePhaseInput,
    UpdatePipeInput,
)

__all__ = [
    "COLORS_VALUES",
    "ConditionExpressionInput",
    "ConditionInput",
    "CreateFieldConditionInput",
    "CreatePhaseFieldInput",
    "FieldConditionActionInput",
    "GraphQLInput",
    "GraphQLJson",
    "PUBLIC_FORM_SUBMITTER_EMAIL_COLLECTION_METHOD_VALUES",
    "PipefyGraphQLId",
    "PublicFormSettingsInput",
    "RepoPreferenceInput",
    "UpdateFieldConditionInput",
    "UpdateLabelInput",
    "UpdatePhaseFieldInput",
    "UpdatePhaseInput",
    "UpdatePipeInput",
    "describe_input_rejection",
]
