# @generated by scripts/generate_graphql_inputs.py — do not edit.
#
# Source: packages/sdk/schema/input_types.json, a pruned snapshot of the
# Pipefy GraphQL schema. Regenerate with:
#     uv run python scripts/generate_graphql_inputs.py
"""Typed mirrors of the Pipefy GraphQL input objects the SDK writes to."""

from __future__ import annotations

from typing import Final

from pydantic import Field

from pipefy_sdk.graphql_inputs._base import (
    GraphQLInput,
    PipefyGraphQLId,
)

# GraphQL enums are soft enums here: the field is typed `str` and any value
# is sent, so a value added server-side works without an SDK release. These
# tuples name the set the schema documents today.

COLORS_VALUES: Final[tuple[str, ...]] = (
    "blue",
    "cyan",
    "gray",
    "green",
    "indigo",
    "lime",
    "pink",
    "purple",
    "orange",
    "red",
    "sky",
    "yellow",
)

PUBLIC_FORM_SUBMITTER_EMAIL_COLLECTION_METHOD_VALUES: Final[tuple[str, ...]] = (
    "required",
    "optional",
    "from_existing_email_field",
)


class ConditionExpressionInput(GraphQLInput):
    """Pipefy GraphQL ``ConditionExpressionInput``.

    Condition's expression inputs
    """

    field_address: str | None = Field(
        default=None, description="The condition field's ID"
    )
    id: PipefyGraphQLId | None = Field(default=None, description="The condition ID")
    operation: str | None = Field(
        default=None,
        description="The condition operation Valid options: equals, not_equals, present, blank, string_contains, string_not_contains, number_greater_than, number_less_than, date_is_today, date_is_yesterday, date_in_current_week, date_in_last_week, date_in_current_month, date_in_last_month, date_in_current_year, date_in_last_year, date_is, date_is_after, date_is_before.",
    )
    structure_id: PipefyGraphQLId | None = Field(
        default=None, description="The structure ID"
    )
    value: str | None = Field(
        default=None, description="The value or field ID to be compared"
    )


class ConditionInput(GraphQLInput):
    """Pipefy GraphQL ``ConditionInput``.

    Condition's inputs
    """

    expressions: list[ConditionExpressionInput | None] | None = Field(
        default=None, description="Array with the expression inputs"
    )
    expressions_structure: list[list[PipefyGraphQLId | None] | None] | None = Field(
        default=None,
        description='Array of arrays with the condition\'s order. Defining groups of "AND" and "OR"',
    )


class FieldConditionActionInput(GraphQLInput):
    """Pipefy GraphQL ``FieldConditionActionInput``.

    Field condition's inputs
    """

    actionId: str | None = Field(
        default=None, description="The condition action Valid options: hide, show."
    )
    id: PipefyGraphQLId | None = Field(default=None, description="The condition ID")
    phaseFieldId: PipefyGraphQLId | None = Field(
        default=None, description="The field ID"
    )
    phaseId: PipefyGraphQLId | None = Field(
        default=None, description="The phase for bulk actions"
    )
    whenEvaluator: bool | None = Field(
        default=None, description="The validation of the conditional"
    )


class CreateFieldConditionInput(GraphQLInput):
    """Pipefy GraphQL ``createFieldConditionInput``."""

    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )
    actions: list[FieldConditionActionInput | None] | None = Field(
        default=None, description="Array with field condition's actions"
    )
    condition: ConditionInput | None = Field(
        default=None, description="The field condition's condition"
    )
    index: float | None = Field(default=None, description="The condition position")
    name: str | None = Field(default=None, description="The field condition name")
    phaseId: PipefyGraphQLId | None = Field(default=None, description="The phase ID")


class CreatePhaseFieldInput(GraphQLInput):
    """Pipefy GraphQL ``CreatePhaseFieldInput``."""

    label: str = Field(description="The field title")
    phase_id: PipefyGraphQLId = Field(description="The phase ID")
    type: PipefyGraphQLId = Field(
        description="The field type Valid options: assignee_select, attachment, checklist_horizontal, checklist_vertical, cnpj, connector, cpf, currency, date, datetime, due_date, email, id, label_select, long_text, number, phone, radio_horizontal, radio_vertical, select, short_text, statement, time."
    )
    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )
    allChildrenMustBeDoneToFinishParent: bool | None = Field(
        default=None,
        description="Connection Field: Whether all children must be done to finish the parent",
    )
    allChildrenMustBeDoneToMoveParent: bool | None = Field(
        default=None,
        description="Connection Field: Whether all children must be done to move the parent",
    )
    canConnectExisting: bool | None = Field(
        default=None,
        description="Connection Field: Whether can connect with existing items",
    )
    canConnectMultiples: bool | None = Field(
        default=None,
        description="Connection Field: Whether is possible to connect with multiple items",
    )
    canCreateNewConnected: bool | None = Field(
        default=None,
        description="Connection Field: Whether is possible to create new connected items",
    )
    childMustExistToFinishParent: bool | None = Field(
        default=None,
        description="Connection Field: Whether a child must exist to finish the parent",
    )
    connectedRepoId: PipefyGraphQLId | None = Field(
        default=None, description="Connection Field: The Repo ID"
    )
    custom_validation: str | None = Field(
        default=None, description="The regex used to validate the field's value"
    )
    description: str | None = Field(default=None, description="The field description")
    editable: bool | None = Field(
        default=None, description="Whether the field is editable"
    )
    help: str | None = Field(default=None, description="The field help text")
    index: float | None = Field(default=None, description="The field index")
    minimal_view: bool | None = Field(
        default=None, description="Whether the field is minimal"
    )
    options: list[str | None] | None = Field(
        default=None, description="The field options"
    )
    required: bool | None = Field(
        default=None, description="Whether the field is required"
    )
    sync_with_card: bool | None = Field(
        default=None, description="Whether the field is sync with the fixed field"
    )


class PublicFormSettingsInput(GraphQLInput):
    """Pipefy GraphQL ``PublicFormSettingsInput``.

    Public form settings's inputs
    """

    afterSubmitMessage: str | None = Field(
        default=None,
        description="The message shown to user after submitting the public form",
    )
    backgroundColor: str | None = Field(
        default=None, description="The background color of the public form (RGB)"
    )
    backgroundImage: str | None = Field(
        default=None, description="The background image URL of the public form"
    )
    brandColor: str | None = Field(
        default=None,
        description="The brand color that will be used in the public form (RGB)",
    )
    title: str | None = Field(default=None, description="Title of the public form")
    logo: str | None = Field(default=None, description="Logo of the public form")
    description: str | None = Field(
        default=None, description="Description of the public form"
    )
    submitButtonText: str | None = Field(
        default=None, description="Text of the submit button on the public form"
    )
    displayPipefyLogo: bool | None = Field(
        default=None, description="Whether to display Pipefy's logo in the public form"
    )
    showSubmitAnotherResponseButton: bool | None = Field(
        default=None, description="Whether its allowed to submit another response"
    )
    submitterEmailCollectionEnabled: bool | None = Field(
        default=None, description="Whether the submitter email collection is enabled"
    )
    submitterEmailCollectionMethod: str | None = Field(
        default=None,
        description="One of PUBLIC_FORM_SUBMITTER_EMAIL_COLLECTION_METHOD_VALUES; any value is sent.",
    )
    submitterEmailFieldId: PipefyGraphQLId | None = Field(
        default=None,
        description="The email field from which submitter email will be collected",
    )
    reuseLastSubmissionResponse: bool | None = Field(
        default=None,
        description="Fill again with the same values that were used on the last submission",
    )


class RepoPreferenceInput(GraphQLInput):
    """Pipefy GraphQL ``RepoPreferenceInput``.

    Repo preference's inputs
    """

    findable: bool | None = Field(
        default=None, description="Can be added to Company portal flag"
    )
    inboxEmailEnabled: bool | None = Field(
        default=None, description="Whether the email inbox is enable"
    )
    mainTabViews: list[str | None] | None = Field(
        default=None, description="The views selected to be shown in the cards"
    )


class UpdateFieldConditionInput(GraphQLInput):
    """Pipefy GraphQL ``UpdateFieldConditionInput``."""

    id: PipefyGraphQLId = Field(description="The field condition ID")
    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )
    actions: list[FieldConditionActionInput | None] | None = Field(
        default=None, description="Array with field condition's actions"
    )
    condition: ConditionInput | None = Field(
        default=None, description="The field condition's condition"
    )
    name: str | None = Field(default=None, description="The field condition name")
    phase_id: PipefyGraphQLId | None = Field(default=None, description="The phase ID")


class UpdateLabelInput(GraphQLInput):
    """Pipefy GraphQL ``UpdateLabelInput``."""

    color: str = Field(description="The label color (hexadecimal)")
    id: PipefyGraphQLId = Field(description="The label ID")
    name: str = Field(description="The label name")
    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )


class UpdatePhaseFieldInput(GraphQLInput):
    """Pipefy GraphQL ``UpdatePhaseFieldInput``."""

    id: PipefyGraphQLId = Field(description="The field ID")
    label: str = Field(description="The field title")
    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )
    allChildrenMustBeDoneToFinishParent: bool | None = Field(
        default=None,
        description="Connection Field: Whether all children must be done to finish the parent",
    )
    allChildrenMustBeDoneToMoveParent: bool | None = Field(
        default=None,
        description="Connection Field: Whether all children must be done to move the parent",
    )
    canConnectExisting: bool | None = Field(
        default=None,
        description="Connection Field: Whether can connect with existing items",
    )
    canConnectMultiples: bool | None = Field(
        default=None,
        description="Connection Field: Whether is possible to connect with multiple items",
    )
    canCreateNewConnected: bool | None = Field(
        default=None,
        description="Connection Field: Whether is possible to create new connected items",
    )
    childMustExistToFinishParent: bool | None = Field(
        default=None,
        description="Connection Field: Whether a child must exist to finish the parent",
    )
    custom_validation: str | None = Field(
        default=None, description="The regex used to validate the field's value"
    )
    description: str | None = Field(default=None, description="The field description")
    editable: bool | None = Field(
        default=None, description="Whether the field is editable"
    )
    help: str | None = Field(default=None, description="The field help text")
    index: float | None = Field(default=None, description="The new field index")
    minimal_view: bool | None = Field(
        default=None, description="Whether the field is minimal"
    )
    options: list[str | None] | None = Field(
        default=None, description="The field options"
    )
    required: bool | None = Field(
        default=None, description="Whether the field is required"
    )
    sync_with_card: bool | None = Field(
        default=None, description="Whether the field is sync with the fixed field"
    )
    uuid: PipefyGraphQLId | None = Field(default=None, description="The field UUID")


class UpdatePhaseInput(GraphQLInput):
    """Pipefy GraphQL ``UpdatePhaseInput``."""

    id: PipefyGraphQLId = Field(description="The phase ID")
    name: str = Field(description="The phase name")
    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )
    can_receive_card_directly_from_draft: bool | None = Field(
        default=None, description="Whether cards can be created directly in the phase"
    )
    color: str | None = Field(
        default=None, description="One of COLORS_VALUES; any value is sent."
    )
    description: str | None = Field(default=None, description="The phase description")
    done: bool | None = Field(default=None, description="Whether it's a final phase")
    lateness_time: int | None = Field(
        default=None, description="The phase's SLA in seconds"
    )
    only_admin_can_move_to_previous: bool | None = Field(
        default=None, description="ARGUMENT IS DEPRECATED!"
    )


class UpdatePipeInput(GraphQLInput):
    """Pipefy GraphQL ``UpdatePipeInput``."""

    id: PipefyGraphQLId = Field(description="The pipe ID")
    clientMutationId: str | None = Field(
        default=None,
        description="A unique identifier for the client performing the mutation.",
    )
    expiration_time_by_unit: int | None = Field(
        default=None, description="The pipe's SLA unit"
    )
    expiration_unit: int | None = Field(
        default=None,
        description="The pipe's SLA expiration period: Minutes: 60, Hours: 3600, Day: 86400.",
    )
    icon: str | None = Field(
        default=None,
        description="The pipe icon Valid options: airplane, at, axe, badge, bag, boat, briefing, bug, bullhorn, calendar, cart, cat, chart-zoom, chart2, chat, check, checklist, compass, contract, dog, eiffel, emo, finish-flag, flame, frame, frog, game, github, globe, growth, hr-process, hr-requests, ice, juice, lamp, lemonade, liberty, like, mac, magic, map, message, mkt-requests, money, onboarding, pacman, pacman1, payable, phone, pipefy, pizza, planet, plug, receivables, receive, recruitment-requests, reload, rocket, sales, skull, snow-flake, star, target, task, task-management, trophy, underwear.",
    )
    color: str | None = Field(
        default=None, description="One of COLORS_VALUES; any value is sent."
    )
    name: str | None = Field(default=None, description="The pipe name")
    noun: str | None = Field(default=None, description="Noun for pipe registries")
    only_admin_can_remove_cards: bool | None = Field(
        default=None, description="Whether only the Admin can delete cards"
    )
    only_assignees_can_edit_cards: bool | None = Field(
        default=None, description="Whether only assignee can edit the card"
    )
    preferences: RepoPreferenceInput | None = Field(
        default=None, description="The pipe preferences"
    )
    public: bool | None = Field(default=None, description="Whether the pipe is public")
    public_form: bool | None = Field(
        default=None, description="Whether the public form is active"
    )
    publicFormSettings: PublicFormSettingsInput | None = Field(
        default=None, description="Public form settings"
    )
    title_field_id: PipefyGraphQLId | None = Field(
        default=None, description="The title field ID"
    )


__all__ = [
    "COLORS_VALUES",
    "ConditionExpressionInput",
    "ConditionInput",
    "CreateFieldConditionInput",
    "CreatePhaseFieldInput",
    "FieldConditionActionInput",
    "PUBLIC_FORM_SUBMITTER_EMAIL_COLLECTION_METHOD_VALUES",
    "PublicFormSettingsInput",
    "RepoPreferenceInput",
    "UpdateFieldConditionInput",
    "UpdateLabelInput",
    "UpdatePhaseFieldInput",
    "UpdatePhaseInput",
    "UpdatePipeInput",
]
