#!/usr/bin/env python3
"""Generate ``docs/mcp/reference.md`` from the registered MCP tools.

Run ``uv run python scripts/gen_mcp_reference.py`` after you change a tool's name,
docstring, parameters, or annotations. ``tests/test_gen_mcp_reference.py`` fails
while the committed page differs from what this script renders.
"""

from __future__ import annotations

import importlib.util
import inspect
import json
import re
from pathlib import Path
from typing import Any, NamedTuple

from mcp.server.mcpserver import MCPServer
from pipefy_mcp.tools.registry import ToolRegistry
from pipefy_mcp.tools.remote_profile import is_remote_tool
from pipefy_mcp.tools.toolsets import DOMAIN_DESCRIPTIONS, DOMAINS

REPO_ROOT = Path(__file__).resolve().parents[1]
REFERENCE = REPO_ROOT / "docs/mcp/reference.md"

# Loaded by path, because a test loads this script by path and `scripts/` is not a package.
_footer_spec = importlib.util.spec_from_file_location(
    "doc_footer", Path(__file__).with_name("doc_footer.py")
)
if _footer_spec is None or _footer_spec.loader is None:
    raise ImportError("scripts/doc_footer.py not found")
_doc_footer = importlib.util.module_from_spec(_footer_spec)
_footer_spec.loader.exec_module(_doc_footer)

_PARAM_LINE = re.compile(r"^\*{0,2}(\w+)(?:\s*\([^)]*\))?:\s*(.*)$")


class Param(NamedTuple):
    name: str
    type: str
    default: str | None  # None means the parameter is required.
    description: str


class ToolEntry(NamedTuple):
    name: str
    summary: str
    read_only: bool
    destructive: bool
    remote: bool
    params: tuple[Param, ...]


class Domain(NamedTuple):
    name: str
    description: str
    tools: tuple[ToolEntry, ...]


def summary_of(docstring: str) -> str:
    first_paragraph = inspect.cleandoc(docstring).split("\n\n", 1)[0]
    return " ".join(line.strip() for line in first_paragraph.splitlines())


def parse_args_section(docstring: str) -> dict[str, str]:
    """Map each parameter in a Google-style ``Args:`` block to its description."""
    lines = inspect.cleandoc(docstring).splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == "Args:")
    except StopIteration:
        return {}
    section_indent = _indent(lines[start])
    param_indent: int | None = None
    parts: dict[str, list[str]] = {}
    current: list[str] | None = None
    for line in lines[start + 1 :]:
        if not line.strip():
            continue
        indent = _indent(line)
        if indent <= section_indent:
            break
        if param_indent is None:
            param_indent = indent
        match = _PARAM_LINE.match(line.strip())
        if indent == param_indent and match:
            current = parts.setdefault(match.group(1), [])
            if match.group(2):
                current.append(match.group(2))
        elif current is not None:
            current.append(line.strip())
    return {name: " ".join(words) for name, words in parts.items()}


def _indent(line: str) -> int:
    return len(line) - len(line.lstrip())


def type_of(schema: dict[str, Any]) -> str:
    """Render a JSON Schema as a short type expression."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(type_of(option) for option in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        items = schema.get("items") or {}
        return f"array of {type_of(items)}" if items else "array"
    return kind or "any"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _render_tool(tool: ToolEntry) -> list[str]:
    flags = [
        flag
        for flag, on in (
            ("read-only", tool.read_only),
            ("destructive", tool.destructive),
            ("remote", tool.remote),
        )
        if on
    ]
    lines = [
        f"### `{tool.name}`",
        "",
        tool.summary,
        "",
        f"Flags: {', '.join(flags) or 'none'}.",
        "",
    ]
    if not tool.params:
        return [*lines, "Takes no parameters.", ""]
    lines += [
        "| Parameter | Type | Default | Description |",
        "|---|---|---|---|",
    ]
    for param in tool.params:
        default = "required" if param.default is None else f"`{param.default}`"
        lines.append(
            f"| `{param.name}` | `{_cell(param.type)}` | {_cell(default)} "
            f"| {_cell(param.description)} |"
        )
    return [*lines, ""]


def render_reference(domains: list[Domain]) -> str:
    lines = [
        "# MCP tool reference",
        "",
        "<!-- Generated by scripts/gen_mcp_reference.py from the registered tools. "
        "Do not edit by hand. -->",
        "",
        "Every tool that `pipefy-mcp-server` registers, grouped by subject domain. "
        "The `remote` flag marks a tool that the remote profile serves. "
        "[`tools/`](tools/cross-cutting.md) explains the behavior that a docstring "
        "does not state.",
        "",
    ]
    for domain in domains:
        lines += [f"## {domain.name}", "", domain.description, ""]
        for tool in domain.tools:
            lines += _render_tool(tool)
    body = "\n".join(lines).rstrip("\n") + "\n"
    return _doc_footer.with_footer(body, str(REFERENCE.relative_to(REPO_ROOT)))


def _entry(tool: Any) -> ToolEntry:
    docstring = tool.description or ""
    described = parse_args_section(docstring)
    schema = tool.parameters
    required = set(schema.get("required", ()))
    params = tuple(
        Param(
            name=name,
            type=type_of(prop),
            default=None if name in required else json.dumps(prop.get("default")),
            description=described.get(name, ""),
        )
        for name, prop in schema.get("properties", {}).items()
    )
    hints = tool.annotations
    return ToolEntry(
        name=tool.name,
        summary=summary_of(docstring),
        read_only=bool(hints and hints.read_only_hint),
        destructive=bool(hints and hints.destructive_hint),
        remote=is_remote_tool(tool),
        params=params,
    )


def collect_domains() -> list[Domain]:
    """Register every tool on a throwaway server and group them by domain."""
    mcp = MCPServer("gen-mcp-reference")
    ToolRegistry(mcp=mcp).register_tools()
    tools = {tool.name: tool for tool in ToolRegistry._live_tools(mcp)}
    return [
        Domain(
            name=name,
            description=DOMAIN_DESCRIPTIONS[name],
            tools=tuple(_entry(tools[tool]) for tool in sorted(members)),
        )
        for name, members in DOMAINS.items()
    ]


def main() -> None:
    REFERENCE.write_text(render_reference(collect_domains()), encoding="utf-8")
    print(f"Wrote {REFERENCE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
